### ISSUE TITLE
W3F Milestone 1

### ISSUE THREAD

**Issue by h4n0** [AdMetaNetwork/admeta-webapp#7]
Checklist to finish M1 of W3F grant. Refer to https://github.com/w3f/Grants-Program/pull/731

## Checklist
- [ ] Documentation for AdMeta Blockchain
- [ ] Documentation for AdMeta WebApp
- [ ] Create docker image for WebApp
